#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

MODE="${1:-full}"
if [[ "$MODE" == "quick" ]]; then
  TOTAL_STAGES=6
elif [[ "$MODE" == "capture" || "$MODE" == "interruptions" ]]; then
  TOTAL_STAGES=10
elif [[ "$MODE" == "recognition" ]]; then
  TOTAL_STAGES=8
else
  TOTAL_STAGES=17
fi

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"
RUN_DIR="${PHYSICAL_RUN_DIR:-$PROJECT_ROOT/.physical-runs/$(date +%Y%m%d-%H%M%S)}"
mkdir -p "$RUN_DIR"
ENV_FILE="$RUN_DIR/results.env"
METRO_LOG="$RUN_DIR/metro.log"
ROWS_LOG="$RUN_DIR/rows.log"
SOAK_LOG="$RUN_DIR/soak.log"
SUMMARY="$RUN_DIR/summary.md"
WORKSPACE="ios/MTGScanNativePreviewSpike.xcworkspace"
METRO_PID=""
SERVICE_PID=""
LOGS_AVAILABLE="no"
SERVICE_ROOT="$(cd "$PROJECT_ROOT/../scanner-accuracy" && pwd)"
APP_ENV_FILE="$PROJECT_ROOT/.env"
SCORE="node $PROJECT_ROOT/scripts/recognition-score.mjs"

stop_metro() {
  if [[ -n "$METRO_PID" ]] && kill -0 "$METRO_PID" 2>/dev/null; then
    kill "$METRO_PID" 2>/dev/null || true
  fi
  if [[ -n "$SERVICE_PID" ]] && kill -0 "$SERVICE_PID" 2>/dev/null; then
    kill "$SERVICE_PID" 2>/dev/null || true
  fi
  if [[ "$MODE" == "recognition" ]]; then
    rm -f "$APP_ENV_FILE"
  fi
}
trap stop_metro EXIT

log_lines() {
  [[ -f "$METRO_LOG" ]] && wc -l < "$METRO_LOG" | tr -d ' ' || echo 0
}

telemetry_json() {
  local minimum_samples="$1" after_line="${2:-0}" after_reset="${3:-no}"
  [[ -f "$METRO_LOG" ]] || return 0
  node -e '
    const [file, minimum, after, afterReset] = process.argv.slice(1);
    const marker = "NATIVE_PREVIEW_TELEMETRY ";
    let lines = require("fs").readFileSync(file, "utf8").split("\n").slice(Number(after));
    if (afterReset === "yes") {
      const reset = lines.findLastIndex((line) => line.includes("manual-reset-accepted"));
      if (reset < 0) process.exit(0);
      lines = lines.slice(reset + 1);
    }
    let found = "";
    for (const raw of lines) {
      const line = raw.replace(/\u001b\[[0-9;]*m/g, "");
      const index = line.indexOf(marker);
      if (index < 0) continue;
      try {
        const value = JSON.parse(line.slice(index + marker.length).trim());
        if (value.sampleCount >= Number(minimum)) found = JSON.stringify(value);
      } catch {}
    }
    process.stdout.write(found);
  ' "$METRO_LOG" "$minimum_samples" "$after_line" "$after_reset" || true
}

telemetry_window() {
  local after_line="$1"
  [[ -f "$METRO_LOG" ]] || return 0
  node -e '
    const [file, after] = process.argv.slice(1);
    const marker = "NATIVE_PREVIEW_TELEMETRY ";
    const lines = require("fs").readFileSync(file, "utf8").split("\n").slice(Number(after));
    const samples = [];
    for (const raw of lines) {
      const line = raw.replace(/\u001b\[[0-9;]*m/g, "");
      const index = line.indexOf(marker);
      if (index < 0) continue;
      try { samples.push(JSON.parse(line.slice(index + marker.length).trim())); } catch {}
    }
    if (samples.length === 0) process.exit(0);
    const detected = samples.filter((sample) => sample.detected);
    const aspects = detected.map((sample) => sample.aspectRatio.toFixed(3));
    process.stdout.write(
      `lines ${samples.length}, refined ${detected.length}, gates ${samples.filter((sample) => sample.gates.all).length}, ` +
      `statuses ${samples.map((sample) => sample.refinementStatus).join("")}, aspects ${aspects.join("/") || "none"}`
    );
  ' "$METRO_LOG" "$after_line" || true
}

field() {
  node -e '
    const value = JSON.parse(process.argv[1])[process.argv[2]];
    process.stdout.write(value === undefined || value === null ? "" : String(value));
  ' "$1" "$2"
}

count_events() {
  local event="$1" after_line="$2"
  [[ -f "$METRO_LOG" ]] || { echo 0; return; }
  tail -n +"$((after_line + 1))" "$METRO_LOG" | grep -ac "\"event\":\"$event\"" || true
}

timed_hold() {
  local key="$1" seconds="$2" expected="$3" before photos failures
  before=$(log_lines)
  pause "Press Enter to start the $seconds-second count."
  for ((remaining = seconds; remaining > 0; remaining -= 5)); do
    say "$remaining seconds left."
    sleep 5
  done
  sleep 1
  photos=$(count_events capture-success "$before")
  failures=$(count_events capture-failure "$before")
  write_env "${key}_PHOTOS" "$photos"
  write_env "${key}_FAILURES" "$failures"
  write_env "${key}_EXPECTED" "$expected"
  say "Photos: $photos (expected $expected). Capture failures: $failures."
}

counted_steps() {
  local key="$1" expected="$2" before photos failures resumes camera_errors
  before=$(log_lines)
  pause "Press Enter to start, then do the steps above."
  pause "Press Enter when every step is done."
  sleep 1
  photos=$(count_events capture-success "$before")
  failures=$(count_events capture-failure "$before")
  resumes=$(count_events capture-resumed-after-gap "$before")
  camera_errors=$(count_events camera-error "$before")
  write_env "${key}_PHOTOS" "$photos"
  write_env "${key}_EXPECTED" "$expected"
  write_env "${key}_FAILURES" "$failures"
  write_env "${key}_RESUMES" "$resumes"
  write_env "${key}_CAMERA_ERRORS" "$camera_errors"
  say "Photos: $photos (expected $expected). Failures: $failures. Resumes: $resumes. Camera errors: $camera_errors."
  if [[ "$photos" == "$expected" ]]; then
    write_env "${key}_RESULT" pass
  else
    write_env "${key}_RESULT" fail
  fi
}

log_has() {
  [[ -f "$METRO_LOG" ]] && grep -aq "$1" "$METRO_LOG"
}

record() {
  local key="$1" prompt="$2"
  ask "$key" "$prompt"
  write_env "$key" "${!key}"
}

write_summary() {
  {
    printf '# Physical run %s\n\n' "$(basename "$RUN_DIR")"
    printf 'Outcome: %s\n\n' "$(_existing RUN_OUTCOME || echo incomplete)"
    printf '| Key | Value |\n| --- | --- |\n'
    if [[ -f "$ENV_FILE" ]]; then
      while IFS='=' read -r key value; do
        printf '| `%s` | %s |\n' "$key" "${value//|/\\|}"
      done < "$ENV_FILE"
    fi
    printf '\nFiles: `results.env`, `metro.log`, `rows.log`, `soak.log` in this folder.\n'
  } > "$SUMMARY"
}

wrap_up() {
  stage "Wrap up"
  stop_metro
  write_summary
  say "Metro is stopped. Your results are saved here:"
  note "$RUN_DIR"
  note "  summary.md   all captured values"
  note "  metro.log    full app log, including NATIVE_PREVIEW_TELEMETRY lines"
  note "  rows.log     telemetry captured after each card row"
  note "  soak.log     one telemetry line per soak minute"
  say "Share summary.md with the agent to record the result on issue #10."
  pause "Press Enter to finish."
  finish
}

stop_run() {
  write_env RUN_OUTCOME "stopped: $1"
  warn "Kill gate: $1"
  pause "Press Enter to save the results and stop."
  wrap_up
  exit 0
}

presentation_row() {
  local key="$1" title="$2" setup="$3" before window
  stage "Card row: $title"
  step "$setup"
  step "Hold the phone roughly above the card for about 10 seconds. Do not tap anything."
  step "The magenta outline is the refined card edge. The thin cyan outline is the rough proposal."
  step "Watch whether magenta sits on the physical outer card edge, and whether it jumps."
  note "If automatic capture is on, a photo here is expected and fine."
  before=$(log_lines)
  pause "Keep the phone on the card. Press Enter after about 10 seconds."
  window=$(telemetry_window "$before")
  if [[ -n "$window" ]]; then
    printf '%s %s\n' "$key" "$window" >> "$ROWS_LOG"
    write_env "${key}_TELEMETRY" "$window"
  fi
  record "${key}_FIT" "Did magenta sit on the outer card edge on all four sides? (yes/partial/no/none shown):"
  record "${key}_JUMPS" "Did magenta jump between positions while the card was still? (no/sometimes/often):"
  record "${key}_NOTES" "Lighting, surface, card, anything odd (Enter to skip):"
  pause
}

find_team_id() {
  local saved="$PROJECT_ROOT/.physical-runs/apple-team-id" profile
  if [[ -n "${MTGSCAN_APPLE_TEAM_ID:-}" ]]; then
    printf '%s' "$MTGSCAN_APPLE_TEAM_ID"
    return
  fi
  if [[ -s "$saved" ]]; then
    cat "$saved"
    return
  fi
  profile=$(find "$HOME/Library/Developer/Xcode/DerivedData" -path '*MTGScanNativePreviewSpike*/Debug-iphoneos/*' \
    -name embedded.mobileprovision 2>/dev/null | head -n1 || true)
  if [[ -n "$profile" ]]; then
    security cms -D -i "$profile" 2>/dev/null | plutil -extract TeamIdentifier.0 raw -o - - 2>/dev/null || true
  fi
}

regenerate_ios() {
  MTGSCAN_APPLE_TEAM_ID="$TEAM_ID" npx expo prebuild --clean --platform ios
  (cd ios && pod install)
}

banner "mtgscan native preview scanner: physical iPhone run"

stage "Preflight"
say "Checking this Mac before you touch the phone."
if [[ -d /Applications/Xcode.app/Contents/Developer ]]; then
  export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
fi
XCODE_VERSION=$(xcodebuild -version 2>/dev/null | head -n1 || true)
say "Xcode: ${XCODE_VERSION:-not found}"
[[ "$XCODE_VERSION" == "Xcode 26.3" ]] || warn "The recorded runs used Xcode 26.3."
command -v node >/dev/null 2>&1 || { warn "node is missing. Install Node.js first."; exit 1; }
if [[ ! -d node_modules ]]; then
  if confirm "node_modules is missing. Run npm ci now?"; then
    npm ci
  else
    warn "The app cannot build without node_modules."
    exit 1
  fi
fi
TEAM_ID=$(find_team_id)
if [[ -z "$TEAM_ID" ]]; then
  say "Your Apple team ID is a 10-character code from developer.apple.com → Account → Membership details."
  ask TEAM_ID "Apple team ID (Enter to skip and choose the team in Xcode instead):"
fi
if [[ -n "$TEAM_ID" ]]; then
  mkdir -p "$PROJECT_ROOT/.physical-runs"
  printf '%s' "$TEAM_ID" > "$PROJECT_ROOT/.physical-runs/apple-team-id"
  say "Signing team: $TEAM_ID. Regenerated projects will keep it."
fi
if [[ -d "$WORKSPACE" ]]; then
  say "A generated iOS project already exists."
  if confirm "Regenerate ios/ with a clean prebuild and pod install? Recommended after any detector change."; then
    regenerate_ios
  fi
else
  say "There is no generated iOS project yet."
  if confirm "Run a clean prebuild and pod install now? This takes a few minutes."; then
    regenerate_ios
  else
    warn "Xcode needs the generated project."
    exit 1
  fi
fi
write_env RUN_STARTED_AT "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
write_env XCODE_VERSION "${XCODE_VERSION:-unknown}"
write_env DETECTOR_COMMIT "$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
pause

if [[ "$MODE" == "recognition" ]]; then
  stage "Start the recognition service"
  if [[ ! -s "$SERVICE_ROOT/.prototype-data/rectified/corpus.json" ]]; then
    say "The rectified candidate set is missing."
    if confirm "Prepare it now? A cold run downloads about 1,300 reference images and takes about 15 minutes."; then
      (cd "$SERVICE_ROOT" && npm run rectified:prepare -w @scanner-accuracy/service)
    else
      warn "Recognition needs the candidate set."
      exit 1
    fi
  fi
  if lsof -nP -iTCP:4317 -sTCP:LISTEN >/dev/null 2>&1; then
    warn "Something is already listening on port 4317. Stop the other service first."
    pause "Press Enter when port 4317 is free."
  fi
  MAC_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)
  [[ -n "$MAC_IP" ]] || { warn "Could not find this Mac's Wi-Fi address."; exit 1; }
  RECOGNITION_TOKEN=$(openssl rand -hex 32)
  say "Starting the service with a new token for this run. Photos go only to this Mac."
  (cd "$SERVICE_ROOT/service" && PROTOTYPE_TOKEN="$RECOGNITION_TOKEN" HOST=0.0.0.0 OCR_ENABLED=0 \
    exec ../node_modules/.bin/tsx src/server.ts) > "$RUN_DIR/service.log" 2>&1 &
  SERVICE_PID=$!
  SERVICE_READY=no
  for _ in $(seq 1 60); do
    if curl -fs "http://127.0.0.1:4317/health" >/dev/null 2>&1; then
      SERVICE_READY=yes
      break
    fi
    sleep 1
  done
  if [[ "$SERVICE_READY" != "yes" ]]; then
    warn "The service did not start. Read $RUN_DIR/service.log."
    exit 1
  fi
  printf 'EXPO_PUBLIC_RECOGNITION_URL=http://%s:4317\nEXPO_PUBLIC_RECOGNITION_TOKEN=%s\n' "$MAC_IP" "$RECOGNITION_TOKEN" > "$APP_ENV_FILE"
  write_env RECOGNITION_URL "http://$MAC_IP:4317"
  printf '  %s✓ service ready%s at http://%s:4317 (log: %s)\n' "$GREEN" "$RESET" "$MAC_IP" "$RUN_DIR/service.log"
  note "If macOS asks whether node may accept incoming connections, click Allow."
  pause
fi

stage "Start Metro"
if lsof -nP -iTCP:8081 -sTCP:LISTEN >/dev/null 2>&1; then
  warn "Something is already listening on port 8081. Stop the other Metro first, or app logs will not reach this run."
  pause "Press Enter when port 8081 is free."
fi
say "Starting Metro in the background. Its output goes to the run folder."
CI=1 EXPO_NO_TYPESCRIPT_SETUP=1 ./node_modules/.bin/expo start --dev-client > "$METRO_LOG" 2>&1 &
METRO_PID=$!
sleep 5
if kill -0 "$METRO_PID" 2>/dev/null; then
  printf '  %s✓ Metro is running%s (log: %s)\n' "$GREEN" "$RESET" "$METRO_LOG"
else
  warn "Metro exited. Read $METRO_LOG, fix the cause, and re-run."
  exit 1
fi
pause

if [[ "$MODE" == "full" ]]; then
  stage "Connect the iPhone"
  step "Connect the iPhone to this Mac with a cable and unlock it."
  step "If the phone asks 'Trust This Computer?', tap Trust and enter the passcode."
  step "If Xcode later says Developer Mode is off: on the phone open Settings → Privacy & Security → Developer Mode, turn it on, and restart the phone."
  step "Keep the phone on the same Wi-Fi network as this Mac so the app can reach Metro."
  pause "Press Enter when the phone is connected and trusted."
fi

stage "Build and run from Xcode"
open "$WORKSPACE"
say "Xcode is opening $WORKSPACE."
[[ "$MODE" != "full" ]] && step "Connect and unlock the iPhone, on the same Wi-Fi as this Mac."
if [[ -z "$TEAM_ID" ]]; then
  step "In the Project navigator, select MTGScanNativePreviewSpike, then the MTGScanNativePreviewSpike target."
  step "Open Signing & Capabilities. Turn on 'Automatically manage signing' and choose your Team."
fi
step "In the toolbar, choose your iPhone as the run destination."
step "Press ⌘R (Product → Run) and wait for the app to open on the phone."
step "If the phone says the developer is untrusted: Settings → General → VPN & Device Management → trust your developer profile, then run again."
step "Allow camera access when the app asks."
step "If the app shows 'No development servers found', tap to enter a URL manually and use http://$(ipconfig getifaddr en0 2>/dev/null || echo YOUR-MAC-IP):8081"
step "If it still cannot connect, check the phone is on the same Wi-Fi, and turn the app on in Settings → Privacy & Security → Local Network."
note "If Xcode reports a bundle identifier or signing error, stop and tell the agent. Do not edit files under ios/."
pause "Press Enter when the camera preview is showing on the phone."
if [[ "$MODE" != "quick" ]]; then
  record DEVICE_MODEL "iPhone model (for example iPhone 16e):"
  record IOS_VERSION "iOS version (Settings → General → About):"
fi
if log_has "camera-format-selected"; then
  LOGS_AVAILABLE="yes"
  printf '  %s✓ app logs are reaching Metro%s, so timing values will be read automatically\n' "$GREEN" "$RESET"
else
  warn "No app log has reached Metro yet. Timing values will be typed in by hand."
fi
write_env LOGS_AVAILABLE "$LOGS_AVAILABLE"
pause

stage "Safety gate"
if grep -q "AUTOMATIC_CAPTURE_ENABLED = true" src/capture/config.ts; then
  EXPECTED_CAPTURE="ON"
  say "This build takes photos automatically. Photos stay on the phone. Nothing is uploaded."
else
  EXPECTED_CAPTURE="OFF"
  say "Automatic capture must stay off for this whole run."
fi
write_env EXPECTED_CAPTURE "$EXPECTED_CAPTURE"
if confirm "Does the top panel say 'Automatic capture: $EXPECTED_CAPTURE'?"; then
  write_env SAFETY_GATE pass
else
  write_env SAFETY_GATE fail
  stop_run "the panel did not show automatic capture as $EXPECTED_CAPTURE"
fi
if [[ "$MODE" == "recognition" ]]; then
  if ! confirm "Does the panel say 'Recognition: waiting for the first photo'? (Close and reopen the app if it says off.)"; then
    stop_run "the app did not load the recognition service settings"
  fi
fi
pause

if [[ "$MODE" == "recognition" ]]; then
  CARDS_FILE="$RUN_DIR/cards.tsv"
  RESULTS_FILE="$RUN_DIR/card-results.ndjson"
  $SCORE cards "$SERVICE_ROOT/.prototype-data/personal-kill-test-manifest.json" > "$CARDS_FILE"
  CARD_TOTAL=$(wc -l < "$CARDS_FILE" | tr -d ' ')

  stage "Card by card"
  say "The wizard names one card at a time from your $CARD_TOTAL-card test list."
  step "Lay the named card flat, hold the phone above it, and wait for the result line at the top of the screen."
  step "Then remove the card and press Enter. Type s and Enter to skip a card you do not have to hand."
  record CARD_LIMIT "How many cards will you present? (Enter for all $CARD_TOTAL):"
  CARD_LIMIT=$(_existing CARD_LIMIT)
  [[ "$CARD_LIMIT" =~ ^[0-9]+$ ]] || CARD_LIMIT=$CARD_TOTAL
  : > "$RESULTS_FILE"
  index=0
  while IFS=$'\t' read -r scryfall_id name set_code number finish <&3; do
    index=$((index + 1))
    (( index <= CARD_LIMIT )) || break
    printf '\n  %sCard %s/%s:%s %s, %s #%s, %s\n' "$BOLD" "$index" "$CARD_LIMIT" "$RESET" "$name" "$set_code" "$number" "$finish"
    before=$(log_lines)
    ask CARD_ACTION "Press Enter after the result shows and the card is removed, or s to skip:"
    if [[ "$CARD_ACTION" == "s" ]]; then
      printf '{"scryfallId":"%s","status":"skipped"}\n' "$scryfall_id" >> "$RESULTS_FILE"
      continue
    fi
    verdict=""
    for _ in $(seq 1 10); do
      verdict=$($SCORE judge-next "$METRO_LOG" "$before" "$scryfall_id" "$name")
      [[ "$verdict" != *'"no-result"'* ]] && break
      sleep 1
    done
    printf '%s\n' "$verdict" >> "$RESULTS_FILE"
    say "$(node -e 'const v = JSON.parse(process.argv[1]); console.log(`${v.status}: top ${v.top ?? "none"}${v.endToEndMs ? `, ${v.endToEndMs} ms` : ""}`)' "$verdict")"
  done 3< "$CARDS_FILE"
  CARD_SUMMARY=$($SCORE summarize "$RESULTS_FILE")
  write_env CARD_SUMMARY "$CARD_SUMMARY"
  say "Summary: $CARD_SUMMARY"
  pause

  stage "Speed run"
  SPEED_FILE="$RUN_DIR/speed-cards.tsv"
  head -n "$(( CARD_LIMIT < 10 ? CARD_LIMIT : 10 ))" "$CARDS_FILE" > "$SPEED_FILE"
  say "Present these cards in this order, as fast as is comfortable:"
  speed_index=0
  while IFS=$'\t' read -r _ name set_code number _; do
    speed_index=$((speed_index + 1))
    note "  $speed_index. $name, $set_code #$number"
  done < "$SPEED_FILE"
  step "For each card: lay it down, wait for the photo count to go up, then swap in the next card."
  step "You do not need to wait for the result line. Do not skip cards."
  SPEED_START_LINE=$(log_lines)
  pause "Press Enter, then start with the first card."
  pause "Press Enter after the last card's result line shows."
  sleep 2
  SPEED_SUMMARY=$($SCORE speed "$METRO_LOG" "$SPEED_START_LINE" "$SPEED_FILE")
  write_env SPEED_SUMMARY "$SPEED_SUMMARY"
  say "Speed run: $SPEED_SUMMARY"
  write_env RUN_OUTCOME "recognition check completed"
  pause
  wrap_up
  exit 0
fi

if [[ "$MODE" == "interruptions" ]]; then
  stage "Background during cooldown"
  step "Before starting: keep every card out of view."
  step "1. Lay one card flat and hold the phone above it until the photo count goes up."
  step "2. Swipe up to go to the home screen. Wait 5 seconds."
  step "3. Reopen the app with the card still in place. Keep it in view for 10 seconds."
  note "Expect one photo: the card must not be photographed again after the app returns."
  counted_steps BACKGROUND_COOLDOWN 1
  pause

  stage "Lock screen during cooldown"
  step "Before starting: move the card out of view for two seconds."
  step "1. Lay the card down and wait for its photo."
  step "2. Press the side button to lock the phone. Wait 5 seconds."
  step "3. Unlock, return to the app, and keep the card in view for 10 seconds."
  note "Expect one photo."
  counted_steps LOCK_COOLDOWN 1
  pause

  stage "Control Center during cooldown"
  step "Before starting: move the card out of view for two seconds."
  step "1. Lay the card down and wait for its photo."
  step "2. Swipe down from the top-right corner to open Control Center. Wait 5 seconds."
  step "3. Close Control Center and keep the card in view for 10 seconds."
  note "Expect one photo."
  counted_steps CONTROL_CENTER 1
  pause

  stage "Card swapped while away"
  step "Before starting: move the card out of view for two seconds."
  step "1. Lay card A down and wait for its photo."
  step "2. Go to the home screen. While the app is away, remove card A."
  step "3. Reopen the app, wait 2 seconds with no card in view, then lay card B down and wait for its photo."
  note "Expect two photos: one for each card."
  counted_steps SWAP_WHILE_AWAY 2
  pause

  stage "Capture after returning"
  step "Before starting: keep every card out of view."
  step "1. Go to the home screen for 5 seconds, then reopen the app."
  step "2. Lay a card down and wait for its photo."
  note "Expect one photo: capture must work normally after the app returns."
  counted_steps AFTER_RETURN 1
  if log_has "fatal-detector-stop"; then
    write_env FATAL_SEEN yes
  fi
  INTERRUPTIONS_GATE=pass
  for key in BACKGROUND_COOLDOWN LOCK_COOLDOWN CONTROL_CENTER SWAP_WHILE_AWAY AFTER_RETURN; do
    [[ "$(_existing "${key}_RESULT")" == "pass" ]] || INTERRUPTIONS_GATE=fail
  done
  log_has "fatal-detector-stop" && INTERRUPTIONS_GATE=fail
  write_env INTERRUPTIONS_GATE "$INTERRUPTIONS_GATE"
  write_env RUN_OUTCOME "interruptions check completed"
  pause
  wrap_up
  exit 0
fi

if [[ "$MODE" == "capture" ]]; then
  stage "Empty surface"
  step "Point the phone at an empty table with no card in view. Keep it there."
  timed_hold EMPTY 15 0
  pause

  stage "Ten card presentations"
  say "Present ten different cards, one at a time, flat on a plain surface."
  step "Lay the card down and hold the phone still above it until the photo count goes up."
  step "Then move the card fully out of view, wait one second, and press Enter."
  step "If no photo comes after about 5 seconds, remove the card anyway and press Enter."
  PRESENTATIONS_EXACT=0
  PRESENTATIONS_MISSED=0
  PRESENTATIONS_DUPLICATE=0
  for card in $(seq 1 10); do
    before=$(log_lines)
    pause "Card $card/10: photo, remove the card, then press Enter."
    sleep 1
    photos=$(count_events capture-success "$before")
    write_env "PRESENTATION_${card}_PHOTOS" "$photos"
    if [[ "$photos" == "1" ]]; then
      PRESENTATIONS_EXACT=$((PRESENTATIONS_EXACT + 1))
    elif [[ "$photos" == "0" ]]; then
      PRESENTATIONS_MISSED=$((PRESENTATIONS_MISSED + 1))
    else
      PRESENTATIONS_DUPLICATE=$((PRESENTATIONS_DUPLICATE + 1))
    fi
    say "Card $card: $photos photo(s)."
  done
  write_env PRESENTATIONS_EXACT "$PRESENTATIONS_EXACT"
  write_env PRESENTATIONS_MISSED "$PRESENTATIONS_MISSED"
  write_env PRESENTATIONS_DUPLICATE "$PRESENTATIONS_DUPLICATE"
  say "Exactly one: $PRESENTATIONS_EXACT. Missed: $PRESENTATIONS_MISSED. Duplicates: $PRESENTATIONS_DUPLICATE."
  record PRESENTATIONS_NOTES "Anything odd, such as a photo of the wrong thing (Enter to skip):"
  pause

  stage "Still card hold"
  step "Before pressing Enter: keep every card out of view."
  step "After pressing Enter: lay one card flat and rest the phone steady above it."
  step "Do not move anything until the count ends. Expect exactly one photo."
  timed_hold STILL_HOLD 20 1
  pause

  stage "Handheld hold"
  step "Before pressing Enter: move the card out of view and keep it out."
  step "After pressing Enter: lay the card down, then hold the phone in your hand above it, as you would when scanning."
  step "Natural hand shake is fine. Do not touch the card during the count. Expect exactly one photo."
  timed_hold HANDHELD_HOLD 20 1
  pause

  stage "Patterned surface"
  step "Before pressing Enter: move the card out of view and keep it out."
  step "After pressing Enter, lay it on a patterned or wood-grain surface and hold the phone above it."
  timed_hold PATTERNED_HOLD 20 1
  record PATTERNED_NOTES "Anything odd (Enter to skip):"
  if [[ "$(_existing EMPTY_PHOTOS)" == "0" && "$PRESENTATIONS_DUPLICATE" == "0" \
    && "$(_existing STILL_HOLD_PHOTOS)" == "1" && "$(_existing HANDHELD_HOLD_PHOTOS)" == "1" \
    && "$(_existing PATTERNED_HOLD_PHOTOS)" -le 1 ]]; then
    write_env EXACTLY_ONE_GATE pass
  else
    write_env EXACTLY_ONE_GATE fail
  fi
  write_env RUN_OUTCOME "capture check completed"
  pause
  wrap_up
  exit 0
fi

if [[ "$MODE" == "quick" ]]; then
  stage "Still card check"
  say "This checks whether the outline stays on the outer card edge."
  step "Lay a black-bordered card flat on a plain surface."
  step "Rest the phone on something steady so the whole card is in view."
  step "Tap 'Reset study' once."
  pause "Press Enter when the phone is steady. The wizard then counts 60 seconds."
  STILL_START_LINE=$(log_lines)
  for remaining in 60 45 30 15; do
    say "$remaining seconds left. Keep still and watch the magenta outline."
    sleep 15
  done
  STILL_WINDOW=$(telemetry_window "$STILL_START_LINE")
  write_env STILL_TELEMETRY "${STILL_WINDOW:-none}"
  say "Detector: ${STILL_WINDOW:-no telemetry found}"
  record STILL_FIT "Did magenta sit on the outer card edge on all four sides? (yes/partial/no/none shown):"
  record STILL_JUMPS "Did magenta jump or disappear while the card was still? (no/sometimes/often):"
  record STILL_NOTES "Card, surface, lighting, anything odd (Enter to skip):"
  write_env RUN_OUTCOME "quick check completed"
  pause
  wrap_up
  exit 0
fi

stage "Empty surface"
step "Point the phone at an empty table or floor with no card in view."
step "Hold it there for 10 seconds and watch the outlines."
pause "Press Enter after 10 seconds."
record EMPTY_FALSE_OUTLINE "Did a magenta outline appear with no card in view? (yes/no):"
record EMPTY_STATUS "Status line at the top:"
pause

stage "Orientation check"
say "This checks the orientation fix. It is a kill gate."
step "Lay one card flat on a plain surface."
step "Move the phone so the card sits near the TOP of the preview. Then near the BOTTOM. Then LEFT. Then RIGHT."
step "Watch the outlines each time. Magenta is the refined edge. Thin cyan is the rough proposal."
note "Pass: both outlines stay on the card and move the same way it moves on screen."
note "Fail: an outline sits on the opposite side, or moves the opposite way."
pause "Press Enter when you have tried all four positions."
record ORIENTATION_NOTES "What did you see? (Enter to skip):"
if confirm "Did both outlines stay on the card and move with it in all four positions?"; then
  write_env ORIENTATION_GATE pass
else
  write_env ORIENTATION_GATE fail
  stop_run "outlines did not follow the card, so the orientation correction failed"
fi
pause

presentation_row ROW_BLACK_BORDER "black-bordered card" \
  "Lay a black-bordered card flat on a plain, light surface."
presentation_row ROW_BORDERLESS "white-bordered or borderless card" \
  "Lay a white-bordered or borderless card flat on the same surface."
presentation_row ROW_SLEEVED "sleeved card" \
  "Lay a card in a sleeve flat on the same surface."
presentation_row ROW_FOIL "foil card" \
  "Lay a foil card flat on the same surface. Note any glare."
presentation_row ROW_ROTATED "rotated card" \
  "Lay a card flat and turn it about 20 degrees on the table."
presentation_row ROW_PARTIAL "partly off-frame card" \
  "Lay a card flat and move the phone until about one fifth of the card is outside the preview."
presentation_row ROW_PATTERNED "patterned surface" \
  "Lay a card flat on a patterned or wood-grain surface."

stage "Timing window"
say "This measures 300 detector samples while nothing moves."
step "Lay a black-bordered card flat on a plain surface."
step "Rest the phone on something steady so the card stays in view."
step "Tap 'Reset study' once to clear old samples."
step "Wait until the panel shows 300/300 samples (about one minute at 5 Hz)."
TIMING_START_LINE=$(log_lines)
pause "Press Enter when the panel shows 300/300 samples."
TIMING_JSON=""
if [[ "$LOGS_AVAILABLE" == "yes" ]]; then
  for _ in $(seq 1 24); do
    if ! grep -aq "manual-reset-accepted" <(tail -n +"$((TIMING_START_LINE + 1))" "$METRO_LOG"); then
      say "Waiting for the 'Reset study' tap. Tap it now if you have not."
    else
      TIMING_JSON=$(telemetry_json 300 "$TIMING_START_LINE" yes)
      [[ -n "$TIMING_JSON" ]] && break
      say "Waiting for 300 samples after the reset. Keep the phone still."
    fi
    sleep 5
  done
fi
if [[ -n "$TIMING_JSON" ]]; then
  for pair in p50Ms:TIMING_P50_MS p95Ms:TIMING_P95_MS maxMs:TIMING_MAX_MS \
    nativeDurationMs:TIMING_NATIVE_MS proposalDurationMs:TIMING_PROPOSAL_MS \
    effectiveHz:TIMING_EFFECTIVE_HZ maxGapMs:TIMING_MAX_GAP_MS \
    consecutiveSlowSamples:TIMING_SLOW_STREAK sampleCount:TIMING_SAMPLES; do
    write_env "${pair#*:}" "$(field "$TIMING_JSON" "${pair%%:*}")"
  done
  printf '%s\n' "$TIMING_JSON" > "$RUN_DIR/timing.json"
else
  warn "No 300-sample telemetry line was found in the log. Type the values from the panel."
  record TIMING_P50_MS "p50 ms:"
  record TIMING_P95_MS "p95 ms:"
  record TIMING_MAX_MS "max ms:"
  record TIMING_NATIVE_MS "Native ms:"
  record TIMING_PROPOSAL_MS "Proposal ms:"
  record TIMING_EFFECTIVE_HZ "Cadence Hz:"
  record TIMING_MAX_GAP_MS "Max gap ms:"
  record TIMING_SLOW_STREAK "Slow streak:"
  record TIMING_SAMPLES "Sample count:"
fi
TIMING_PASS=$(node -e '
  const [p95, hz, samples] = process.argv.slice(1).map(Number);
  process.stdout.write(samples >= 300 && p95 < 20 && hz >= 4.5 ? "pass" : "fail");
' "$(_existing TIMING_P95_MS)" "$(_existing TIMING_EFFECTIVE_HZ)" "$(_existing TIMING_SAMPLES)")
write_env TIMING_GATE "$TIMING_PASS"
say "p95 $(_existing TIMING_P95_MS) ms (needs < 20), cadence $(_existing TIMING_EFFECTIVE_HZ) Hz (needs ≥ 4.5)."
if log_has "fatal-detector-stop"; then
  write_env FATAL_SEEN yes
  stop_run "the app logged a fatal detector stop"
fi
[[ "$TIMING_PASS" == "pass" ]] || stop_run "timing gate failed"
pause

stage "15-minute soak"
say "The earlier gates held. This soak watches the detector for 15 minutes."
if ! confirm "Run the 15-minute soak now?"; then
  write_env SOAK "skipped"
  write_env RUN_OUTCOME "completed without soak"
  wrap_up
  exit 0
fi
step "Keep the card flat and the phone resting steady, as in the timing window."
step "In Xcode, open the Debug navigator (⌘7) and select Memory."
record SOAK_MEMORY_START_MB "Memory now, in MB:"
SOAK_FAILED=""
for minute in $(seq 1 15); do
  sleep 60
  minute_json=$(telemetry_json 0 0)
  printf '%s %s\n' "$minute" "${minute_json:-none}" >> "$SOAK_LOG"
  if [[ -n "$minute_json" ]]; then
    say "minute $minute/15: p95 $(field "$minute_json" p95Ms) ms, $(field "$minute_json" effectiveHz) Hz, slow streak $(field "$minute_json" consecutiveSlowSamples)"
  else
    say "minute $minute/15: no telemetry in the log"
  fi
  if log_has "fatal-detector-stop"; then
    SOAK_FAILED="fatal detector stop during soak"
    break
  fi
done
record SOAK_MEMORY_END_MB "Memory now, in MB:"
record SOAK_TEMPERATURE "Did the phone show a temperature warning or get hot? (no/warm/hot/warning):"
record SOAK_CRASH "Did the app crash, freeze, or stall? (no/yes):"
record SOAK_NOTES "Anything else (Enter to skip):"
if [[ -n "$SOAK_FAILED" ]]; then
  write_env SOAK fail
  stop_run "$SOAK_FAILED"
fi
write_env SOAK done
write_env RUN_OUTCOME "completed"
pause

wrap_up
